### ISSUE TITLE
Academic Icons are missing

### ISSUE THREAD

**Issue by ivantishchenko** [sourcethemes/academic-kickstart#113]
For some reason Academic Icons are not displayed.

I observed the same behaviour at https://academic-demo.netlify.app/. The google scholar icon is missing
![image](https://user-images.githubusercontent.com/11161694/91054979-4fc8eb00-e624-11ea-9862-4011269b3cba.png)
 
My _index.md is the following:

```
social:
- icon: envelope
  icon_pack: fas
  link: 
- icon: github
  icon_pack: fab
  link: 
- icon: twitter
  icon_pack: fab
  link: 
- icon: google-scholar
  icon_pack: ai
  link: 
```
